### ISSUE TITLE
Studying For, And Passing, The dbt Certification Exam From Two Viewpoints

### ISSUE THREAD

**Issue by stephenon1309** [fishtown-analytics/docs.getdbt.com#1971]
### Contact Details

stephen.oneill

### I have read the dbt Developer Blog contribution guidelines.

- [X] I have read the dbt Developer Blog contribution guidelines.

### Which of these best describes you?

- [X] I am a dbt Community member or partner contributing to the Developer Blog
- [ ] I work for dbt Labs and am creating this issue for a community or marketing approved piece.

### What is the topic of your post?

This article will outline how two members of the Montreal Analytics team, one senior analytics engineer with 3 years of dbt experience [Callie] and one junior analytics engineer with 6 months dbt experience [Jade], prepared for dbt certification. 

The article will discuss how each person prepared for the certification, their experience with the certification; what aspects of their preparation was most valuable, and ultimately how they fared taking the exam. The writers will also share their personal study material as an added resource to readers, as further outlined below.

### Link to an initial outline.

This article is meant to be used as a read-along while studying for the dbt certification exam, giving some insight into the test preparation and taking process for those who may not know others taking the test. We’d like to compare Callies experience taking the test to Jades so readers can gauge what may be the best preparation for themselves. We will include a few sample questions (made by us not taken from dbt) and might attach our flashcards resource. Not a study guide, but more like notes from a friend who believes in you!

**Part One:** A Little blurb on each of the writers, what brought us to the exam, and our prior dbt experience

**Part Two:** How each of the writers prepared for the exam - the resources used, their exam taking style, previous experience with similar exams as well as an outline on what to expect on test day, in terms of general setup and monitor edu info.

**Part Three:** Taking the test - after test thoughts/ feelings on how each writer find it, what aspects of our prep were helpful/not necessary types (and formats!) of questions 

**Part 3.1:** Retaking the test… Jade failed the test on her first try, so here is what tripped her up, how she changed her approach and in general some confidence boosting remarks

**Part Four:** Now that we’re dbt official, where to next?

**Part Five**  A link here to a resource (flashcards) (if acceptable)

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309, I'm Kira, a technical writer here at dbt Labs and will be the dedicated resource for y'all for this piece!

The team is super hyped for this piece and the outline sounds amazing. Honestly cannot wait to get practitioner eyes on this.

The general turnaround time for Developer Blog posts is 6 weeks (from GitHub Issue submission to publication), but we work with you all on the timeline that's best for you. Since this outline looks awesome, next step for you all is to send over a draft from your outline (feel free to just post the link to it in the original description for this issue), so that I can review and make any suggestions (editorial or technical). 

Lmk how that sounds to you all or if you have any questions!

**Comment by stephenon1309** [comment]
Hi Kira,

Thank you so much for such positive feedback - I will share this with my team! That timeline should work work with us - I will check back in with the writers and get a timeline for you, for sharing a first draft!

**Comment by stephenon1309** [comment]
Hi @KiraFuruichi - just wanted to update you on progress on our end - both authors have been pretty swamped so apologies on delays, but they are hoping to have a first draft by Monday or Tuesday of next week!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309 thank you for the update! Absolutely no rush on getting drafts in since we work on a timeline that's best for you all. Excited to read some drafts though!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309, I realized I haven't checked in for a while here! How are things looking for your team? 😄

**Comment by stephenon1309** [comment]
Hi @KiraFuruichi , apologies for not following up on an update with this! One our team members writing this had some unexpected decreased capacity over the past few weeks and so this had to be pushed back a bit in priority - very sorry I forgot to let you know! We are aiming for end of November for submission, if that timeline is ok?

**Comment by KiraFuruichi** [comment]
That sounds great @stephenon1309 !  No rush on our end :) Lmk when y'all have a draft ready and I'm happy to take a look.

**Comment by KiraFuruichi** [comment]
Happy new year, @stephenon1309 ! I just wanted to check-in to see if the team was still interested in pursuing this article :)

**Comment by stephenon1309** [comment]
Hi @KiraFuruichi  - I'm so sorry this has taken so long to get get a draft back to you, one of the author's capacity changed and was unable to dedicate time to this until recently. Happy to finally present you with a v1 draft for your review.

https://docs.google.com/document/d/13FFDiwy9A8AxoEMBj5VrmlwwCAwp7hpaCeJphWUpplY/edit

**Comment by KiraFuruichi** [comment]
Amazing, thanks @stephenon1309, excited to give it a read + editing pass next week!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309 went through and gave this a big editing pass. I really appreciated the humanness of this draft and I think the humbling nature of test taking will speak to readers. Bigger-picture-wise: I think readers and prospective certification candidates would love to see more on specific resources, docs, or topics covered in the exam. 

Please let me know how y'all feel about the feedback! I'm excited to work with y'all on getting this live :)

**Comment by stephenon1309** [comment]
Hi @KiraFuruichi - the members of my team who have worked on this have informed me that they have resolved some of your comments and to the document. Could you please review? Thanks!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309  thank you! This is on my docket today to review :)

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309 thanks for your patience here! Just had my colleague take a quick look and he left some minor comments if Callie and Jade wanted to address them, but otherwise, I think we're good to publish! Lmk once they've had some time to address those and I'll start getting this live and promoted :)

**Comment by stephenon1309** [comment]
Hey @KiraFuruichi Jade & Callie have both reviewed and addressed comments - they are happy for this to be pushed live! Thank you so much for your work, and patience, on this - it took us a while to get it over the line!

**Comment by KiraFuruichi** [comment]
Awesome I'll work on getting this live in the next few days. @stephenon1309 can you have Callie and Jade DM me on the dbt Community Slack and send both:
- a picture for their author bio
- an author bio

Thanks!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309! Can you have Callie and Jade either DM on the Community Slack or post here author bios + author pics, thank you!

**Comment by KiraFuruichi** [comment]
Hey @stephenon1309 [this is live](https://docs.getdbt.com/blog/tips-for-the-dbt-certification-exam)! We'll be promoting on our social later this week, but feel free to share with your network. Thanks again for opening up this issue, I'm glad we could all collaborate on this :)
