### ISSUE TITLE
Multi-project collaboration - Milestone 2

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/docs.getdbt.com#3362]
```[tasklist]
### Namespacing & XP ref
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3571
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3572
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3550
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3573
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3574
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3632
```
```[tasklist]
### Model governance: UX improvements
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3357
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3745
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3570
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3282
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3454
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3475
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3569
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3496
- [ ] https://github.com/dbt-labs/docs.getdbt.com/issues/3649
```
