### ISSUE TITLE
Refresh docs on materialized views

### ISSUE THREAD

**Issue by dataders** [fishtown-analytics/docs.getdbt.com#4196]
### Contributions

- [ ] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

- https://docs.getdbt.com/reference/resource-configs/postgres-configs#materialized-views
- https://docs.getdbt.com/reference/resource-configs/snowflake-configs#dynamic-tables
- https://docs.getdbt.com/reference/resource-configs/bigquery-configs#materialized-view
- https://docs.getdbt.com/reference/resource-configs/databricks-configs#materialized-views-and-streaming-tables

### What part(s) of the page would you like to see updated?

```[tasklist]
### Tasks
- [ ] perhaps add a standalone generic "materialized view page"?
- [ ] revert #3812 and #3779 and bring back BigQuery MVs
- [ ] versionblock current MV/DT caveats into `1.6`, create new `1.7` block with the remaining caveats
- [ ] discuss in more detail the concept
- [ ] update materialized view / dynamic table docs to reflect caveats that no longer
```

### Additional information

Following on from #3593, #3779 and #4045

**Comment by runleonarun** [comment]
_reached out to @dataders to understand whether this is a docs request or Anders has got it covered. Also if docs team support is needed, some of the bullets need more info_

**Comment by amychen1776** [comment]
Closing this because we have covered most of this and the other ones - we don't have short term plans to support
