### ISSUE TITLE
dbt explorer has replaced the legacy dbt docs for dbt cloud users

### ISSUE THREAD

**Issue by runleonarun** [fishtown-analytics/docs.getdbt.com#4882]
### Contributions

- [x] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

* [Artifacts]https://docs.getdbt.com/docs/deploy/artifacts
* [Build and view docs(]https://docs.getdbt.com/docs/collaborate/build-and-view-your-docs#viewing-documentation

### What part(s) of the page would you like to see updated?

dbt explorer has replaced the legacy dbt docs for dbt cloud users. 
```[tasklist]
### Tasks
- [ ] Review and update the [Artifacts](https://docs.getdbt.com/docs/deploy/artifacts) page This page refers to selecting the primary job for documentation. With the documentation tab removed from the IDE and Explorer fetching info from the "Prod" environment, this section might need some adjustments. For example: [ ] Update "you should only associate one production job with a given project to produce the project's artifacts" [ ] All screenshots are out of date [ ] Proof the rest of the page for the old UI.
- [ ] Review the [build and view your docs](https://docs.getdbt.com/docs/collaborate/build-and-view-your-docs#viewing-documentation) page. [ ] The viewing documentation section at least needs a note about how legacy docs will be the only available option for dev plans.  [ ] The [generating documentation](https://docs.getdbt.com/docs/collaborate/build-and-view-your-docs#generating-documentation) might also require some tweaks.
- [ ] Review [Discovery API page](https://docs.getdbt.com/docs/dbt-cloud-apis/discovery-api) > Discovery tab. Use screen shots of Explorer instead of legacy docs:![image](https://github.com/dbt-labs/docs.getdbt.com/assets/3880403/f7beb481-2744-499b-80e5-50db5213a7d8)
- [ ] Must coordinate with PM/PMM on when to update the messaging 
```

**Comment by mirnawong1** [comment]
@migueldichoso from the CS team flagged that a user was confused on where or how to find the legacy docs page. see [slack thread](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1710156298842929)

**Comment by mirnawong1** [comment]
i have taken over this feature now (pod 3) and am going to address this

**Comment by mirnawong1** [comment]
add'l issue raised in april : https://github.com/dbt-labs/docs.getdbt.com/issues/5304

**Comment by mirnawong1** [comment]
also raised today here: https://dbt-labs.slack.com/archives/C02NCQ9483C/p1718204765524829
